Time to play:
Loading lists of data
graph data Data(x=[81, 1], edge_index=[2, 324], y=[81], pos=[81, 2])
Traceback (most recent call last):
  File "/home/dami/Inverse_GNN/apply_GS.py", line 58, in <module>
    print("fukc",transformedgraph[1])
IndexError: index 1 is out of bounds for axis 0 with size 1
Traceback (most recent call last):
  File "/home/dami/Inverse_GNN/train_FEMgpu.py", line 258, in <module>
    train_loss = train(fopt,epoch,lamda)
  File "/home/dami/Inverse_GNN/train_FEMgpu.py", line 173, in train
    with open("/home/dami/Inverse_GNN/FEM_output/gspdata","rb") as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dami/Inverse_GNN/FEM_output/gspdata'
(81, 81)
(1, 3, 31)
(100, 3, 81)