Time to play:
Loading lists of data
graph data Data(x=[81, 1], edge_index=[2, 324], y=[81], pos=[81, 2])
Traceback (most recent call last):
  File "/home/dami/Inverse_GNN/apply_GS.py", line 69, in <module>
    print(transformedgraph[i,:,:].squeeze().shape)
IndexError: index 1 is out of bounds for axis 0 with size 1
(81, 81)
(1, 3, 31)
(100, 3, 81)
(81, 3)
(3, 31)
(81, 3)